# Generated by Django 3.2.12 on 2025-02-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
