# Generated by Django 3.2.12 on 2025-02-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones_app', '0004_comentario_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/video/'),
        ),
    ]
